### ISSUE TITLE
CC3.0 Lizenz inkompatibel zur ODbL OpenStreetMap Lizenz

### ISSUE THREAD

**Issue by mika-data** [codeforcologne/giesstKoelle#1]
die Daten von http://giesst.koeln dürfen wir leider nicht verwenden. Unter “Rechtliche Hinweise” steht klar drin:

“Urheberrecht

Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Sie sind mit einer Creative Commons Lizenz urheberrechtlich geschützt. Sofern nicht anders angegeben, stehen die Inhalte dieser Seite unter der Creative Commons Namensnennung 3.0 DE Lizenz. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.”

Die “Creative Commons Namensnennung 3.0 DE Lizenz” ist leider nicht mit der ODbL-Lizenz von OSM kompatibel.

**Comment by OpenDEM** [comment]
"...Sofern nicht anders angegeben..."

Bei den Daten, die zum Download angeboten werden, stehen noch die expliziten Lizenzen:

Lizenzbedingungen:

    Spalte "source" = Stadt Köln CC BY 3.0 DE
    Spalte "source" = crowd - unter einer der folgenden Lizenzen
        Open Data Commons Public Domain Dedication and Licence (ODC PDDL)
        Data licence Germany - Zero - Version 2.0 (dl-de/zero-2-0)

Es dürfen also leider nur Daten in OSM genutzt werden, wo in der Spalte source den Wert "crowd" hat.
